apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuber-ingress
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: kuber-service
            port:
              number: 80
      - path: /v1
        pathType: Exact
        backend:
          service:
            name: kuber-service2
            port:
              number: 80       
