apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuber-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: kuber-app
        image: roflmaoinmysoul/otus:v1.0