apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemonset
  namespace: default
  labels:
    app: monitoring-daemonset
spec:
  selector:
    matchLabels:
      app: monitoring-daemonset
  template:
    metadata:
      labels:
        app: monitoring-daemonset
    spec:
      # Толерантности для запуска на master узлах
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: monitoring-container
        image: busybox:1.35
        command: ["/bin/sh"]
        args: 
          - "-c"
          - |
            echo "Monitoring daemon started on node: $NODE_NAME"
            echo "Pod name: $HOSTNAME"
            echo "Started at: $(date)"
            
            # Мониторинг каждые 10 секунд
            while true; do
              echo "[$(date)] Monitoring node resources..."
              echo "  - Node: $NODE_NAME"
              echo "  - Pod: $HOSTNAME"
              echo "  - Uptime: $(uptime)"
              sleep 10
            done
        # Переменные окружения
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Проверки жизнеспособности
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep -q 'monitoring'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        # Ресурсы
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        # Безопасность
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      # Перезапуск Pod'а при сбое
      restartPolicy: Always
      # Селектор узлов (опционально)
      # nodeSelector:
      #   kubernetes.io/os: linux
